services:
  _defaults:
    autowire: true
    autoconfigure: true

  inisire\RPC\:
    resource: '../../../src/*'

  inisire\DataObject\:
    resource: '../../../../data-object/src/'

  inisire\RPC\Routing\RouteLoader:
    tags: ['routing.loader']

  inisire\RPC\DataObject\DataSerializerProviderFactory:
    arguments: [ !tagged_locator {tag: 'object_reference.loader'} ]

  inisire\DataObject\DataSerializerProvider:
    factory: ['@inisire\RPC\DataObject\DataSerializerProviderFactory', 'create']

  inisire\RPC\Entrypoint\EntrypointRegistry:
    arguments:
      $container: !tagged_locator { tag: 'rpc.command_handler' }