services:
  _defaults:
    autowire: true
    autoconfigure: true

  inisire\RPC\:
    resource: '../../../src/*'

  inisire\DataObject\:
    resource: '../../../../data-object/src/'

  inisire\RPC\Loader\RouteLoader:
    arguments: [ !tagged_locator { tag: 'rpc.command_handler' } ]
    tags: ['routing.loader']

  inisire\RPC\Controller\BusBridgeController:
    arguments:
      $entrypoints: !tagged_locator { tag: 'rpc.command_handler' }