services:
  _defaults:
    autowire: true
    autoconfigure: true

  inisire\CQRS\:
    resource: '../../'

  inisire\DataObject\:
    resource: '../../../../data-object/src/'

  inisire\CQRS\RPC\RouteLoader:
    arguments: [ !tagged_locator { tag: 'messenger.message_handler' } ]
    tags: ['routing.loader']